<?php ?>
<div class="container py-5">
    <div class="row">
        <div class="col-12 order-1 order-lg-0">
            <div class="row">
                <div class="col-12">
                    <div id="listShow" class="row">

                        <?php
                        foreach ($imagenes as $img) {
                            ?>

                            <div class="col-12 col-md-6 col-xl-3 my-3 catprod">
                                <div class="item-product-car bubble-parent">
                                    <div class="d-none d-md-block">
                                        <img class="zoom-it w-100 img-fluid" src="/imagenes/public/img/1/<?php echo $img['file_name']; ?>" alt=""/>
                                        <p class="title mt-3"><?php echo $img['title']; ?></p>
                                    </div>
                                    <div class="d-block d-md-none">
                                        <img class="zoom-it w-100 img-fluid" src="/imagenes/public/img/1/<?php echo $img['file_name']; ?>" alt=""/>
                                        <p class="title mt-3"><?php echo $img['title']; ?></p>
                                    </div>
                                    <div id="buttons-container" class="d-flex justify-content-center mt-3 mb-4">
                                        <a role="button" class="btn btn-danger mx-1 mb-2" href="javascript:deleteImageModal(<?php echo $img['img_id']; ?>);">
                                            <i class="fas fa-trash-alt"></i>
                                            <span>Eliminar</span>
                                        </a>
                                    </div>

                                </div>                            
                            </div>

                        <?php } ?>

                    </div>
                    <div class="row">
                        <div class="col-12">
                            <div class="d-flex justify-content-center justify-content-lg-end">
                                <div id="pager" class="turn-page"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>